[package]
name = "worldclock-tui"
version = "1.0.1"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/Feriixu/worldclock-tui-rs"
description = "A small Rust terminal UI that shows the current time across UTC offsets or the full IANA timezone list."
license = "Apache-2.0 OR MIT"

[[bin]]
name = "worldclock"
path = "src/main.rs"

[dependencies]
chrono = "0.4.45"
chrono-tz = "0.10.4"
crossterm = "0.29.0"
ratatui = "0.30.2"
